import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { getReportStatus, generateReport } from '../../services/reportService';

export default function ReportsPage() {
  const navigate = useNavigate();
  const [status, setStatus] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);

  const fetchStatus = async () => {
    try {
      const data = await getReportStatus();
      setStatus(data);
      return data;
    } catch (err: any) {
      setError(err.message);
      return null;
    }
  };

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await generateReport();
      setStatus(data);
    } catch (err: any) {
      setError(err.response?.data?.message || err.message);
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate report on page load
  useEffect(() => {
    if (!hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="max-w-4xl mx-auto">
      <h1 className="text-2xl font-bold mb-6">📊 Allure Reports</h1>

      <div className="bg-white rounded-lg shadow p-6">
        <div className="flex items-center gap-4 mb-6">
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="bg-primary text-white px-5 py-2.5 rounded-lg hover:bg-primary-dark disabled:opacity-50"
          >
            {loading ? '⏳ Generating...' : '📊 Regenerate Report'}
          </button>
          <button
            onClick={fetchStatus}
            className="bg-gray-200 text-gray-700 px-4 py-2.5 rounded-lg hover:bg-gray-300"
          >
            🔄 Refresh Status
          </button>
          <button
            onClick={() => navigate('/execution')}
            className="bg-gray-200 text-gray-700 px-4 py-2.5 rounded-lg hover:bg-gray-300"
          >
            ← Back to Execution
          </button>
        </div>

        {/* Loading */}
        {loading && (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-4 text-center">
            <div className="animate-spin inline-block w-6 h-6 border-4 border-primary border-t-transparent rounded-full mb-2"></div>
            <p className="text-sm text-yellow-700">⏳ Generating Allure report from test results...</p>
          </div>
        )}

        {error && (
          <div className="mb-4 p-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm">
            ❌ {error}
          </div>
        )}

        {status && (
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className={`w-3 h-3 rounded-full ${status.available ? 'bg-green-400' : 'bg-gray-300'}`} />
              <span className="text-sm font-medium">
                {status.available ? '✅ Report Available' : 'No Report Generated Yet'}
              </span>
            </div>
            {status.available && (
              <>
                <p className="text-sm text-gray-600">
                  Report URL:{' '}
                  <a
                    href={status.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary underline"
                  >
                    {status.url}
                  </a>
                  <a
                    href={status.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="ml-3 text-sm bg-blue-100 text-blue-700 px-3 py-1 rounded hover:bg-blue-200"
                  >
                    ↗ Open in New Tab
                  </a>
                </p>
                <iframe
                  src={status.url}
                  className="w-full h-[600px] border border-gray-200 rounded-lg mt-4"
                  title="Allure Report"
                />
              </>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
